version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_pwd
  adminer:
    image: 'adminer'
    ports:
      - "8080:8080"   
  redis:
    image: 'redis:latest'
  nginx:
    build:
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_pwd
      - PGPORT=5432
  client:
    build:
      context: ./client
  worker:
    build:
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


